### ISSUE TITLE
Add functionality broken

### ISSUE THREAD

**Issue by Thirtybird** [solo123/gbm_plugin#10]
Unable to add bookmarks through the interface.  No error is given.

Try to add bookmark, the status briefly changes to "reload bookmarks.." and then "bookmarks reloaded", reload the bookmarks on the bookmarks tab and the added bookmark is not there.

logging into www.google.com/bookmarks/ verifies no bookmark has been added.  Adding bookmarks through that website works, and when I reload the bookmarks in the extension, they do show up.

I have uninstalled application, shut down all browser windows, and re-installed to no effect

**Comment by solo123** [comment]
I try this function and it works here. i'm not sure maybe is about your running enviroment. if this bug still bother you, will you please run the "test" on the "tools" tab and show me the test result?

**Comment by Thirtybird** [comment]
> > Bookmarks Obj init............... PASSED = [object Object]
> > Is empty......................... PASSED = null
> > Load bookmarks................... PASSED = [object Object]
> > Check SIG........................ PASSED = OeocaunUYenHlQb1fgGOJQ
> > Save bookmark.................... PASSED = false

**Comment by Thirtybird** [comment]
and today it works.  I saw something in the notes about switching to https and I updated the API url's to use https and then it starts working.

**Comment by solo123** [comment]
maybe on Feb or March, google bookmarks api have to use HTTPS. up till now google didnot provide it's bookmarks API.  so this plugin maybe not work sometime there are changes.
