### ISSUE TITLE
Feature Request: Combine Search and Labels tabs

### ISSUE THREAD

**Issue by patrickberkeley** [solo123/gbm_plugin#4]
There's a lot of duplication between these two tabs. The only thing that's nice about the Labels tab is that you can select multiple. I suggest just adding that functionality to the Bookmarks tab and getting rid of the Labels tab.

The Bookmarks tab is much easier to use than the Labels tab because you don't have to expand anything to see the results; they just appear after you click. Nice.

**Comment by solo123** [comment]
multi-label selection have some options, like and/or etc. i can't find a clear way to show that, so i just add "Labels" tab to do that.
